### ISSUE TITLE
Detect SMS in background and start service

### ISSUE THREAD

**Issue by manumaticx** [m1ga/ti.miga.sms.receive#1]
Hi Michael,

is it possible to detect an incoming SMS when the App is not running? I need to start a background service when the phone receives a SMS.

Also, is it possible to receive SMS on specific ports?

**Comment by m1ga** [comment]
about the port:

http://stackoverflow.com/a/17057402/5193915
You can change the port number in den manifest (https://github.com/m1ga/ti.miga.sms.receive/blob/master/android/timodule.xml#L21)

service:

Perhaps using it together with Ben's AlarmManger (https://github.com/benbahrenburg/benCoding.AlarmManager) would already work as a backgroundService and then start a different service; I didn't try that but will do some testing.

**Comment by manumaticx** [comment]
Thanks! Let me do the testing - I'll let you know!

**Comment by manumaticx** [comment]
@m1ga Allright, I managed it with my own BroadcastReceiver which starts my javascript service. It's very simple but it works fine.
