### ISSUE TITLE
Ti SDK 7+ compatible version?

### ISSUE THREAD

**Issue by qasim90** [m1ga/ti.miga.sms.receive#5]
The title says all :)

**Comment by m1ga** [comment]
Sure: https://github.com/m1ga/ti.miga.sms.receive/releases/tag/2.0.0

**Comment by qasim90** [comment]
Thanks for the prompt response. Is it possible to include the compiled distribution .zip? I can't find it anywhere.

**Comment by m1ga** [comment]
sorry, didn't see that there was an error while uploading the binary. It is available now at https://github.com/m1ga/ti.miga.sms.receive/releases/tag/2.0.0

**Comment by qasim90** [comment]
Thank you very much. Really appreciated.
